version: '3'
services:
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: wp_host4
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 123

  wp:
    build: .
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: wp_host4
    links:
      - db
      
  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     ports:
       - "0.0.0.0:4090:80"
     links:
       - db:db
     environment:
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: 123
        MYSQL_ROOT_PASSWORD: 123
volumes:
  container-volume: